#!/usr/bin/env python3
# Copyright (c) 2026 Jonathan Beri
# SPDX-License-Identifier: Apache-2.0
"""Convert tests/vectors/*.json into a C include for the codec ztest.

Output is checked in (tests/codec/src/vectors.inc); CI verifies it is in
sync by regenerating and diffing.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "tests" / "codec" / "src" / "vectors.inc"


def emit(name: str, data: bytes) -> str:
    body = ", ".join(f"0x{b:02x}" for b in data)
    return f"static const uint8_t {name}[] = {{{body}}};\n"


def main() -> None:
    messages = json.loads((ROOT / "tests" / "vectors" / "prov_messages.json").read_text())
    frames = json.loads((ROOT / "tests" / "vectors" / "pouch_frames.json").read_text())

    out = ["/* Generated by scripts/vectors_to_c.py — do not edit. */\n"]
    for section in ("requests", "responses"):
        for name, hexstr in messages[section].items():
            out.append(emit(f"vec_{name}", bytes.fromhex(hexstr)))
    for name, hexstr in frames.items():
        out.append(emit(f"frame_{name}", bytes.fromhex(hexstr)))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(out))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
